include_guard(GLOBAL)

option(USERVER_MONGODB_USE_STATIC_LIBS "Link statically with mongoc" ON)

find_package(bson-1.0 QUIET CONFIG)
find_package(mongoc-1.0 QUIET CONFIG)
if(bson-1.0_FOUND AND mongoc-1.0_FOUND)
  message(STATUS "Mongoc: using config version")
  if(USERVER_MONGODB_USE_STATIC_LIBS)
    add_library(bson ALIAS mongo::bson_static)
    add_library(mongoc ALIAS mongo::mongoc_static)
  else()
    add_library(bson ALIAS mongo::bson_shared)
    add_library(mongoc ALIAS mongo::mongoc_shared)
  endif()
else()
  find_package(bson REQUIRED)
  find_package(mongoc REQUIRED)
endif()

